name: Full Deploy Pipeline

on:
  push:
    name: Full Deploy Pipeline

                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1
              - name: Setup Terraform
                name: Full Deploy Pipeline
